site_name: FHIR Kindling
repo_url: https://github.com/migraf/fhir-kindling
edit_uri: blob/main/docs/
theme:
  name: material
  logo: 'assets/logo.png'
  favicon: 'assets/logo.png'
  features:
    - navigation.tracking
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
site_dir: public

nav:
  - Home: index.md
  - User Guide:
    - Connect to a FHIR server: connect.md
    - Query a server: query.md
    - Add resources: add.md
    - Delete resources: delete.md
    - Update resources: update.md
    - Transfer resources: transfer.md
    - Data Science: ds.md
  - API docs: api.md


markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocstrings
  - search
