version: '3.8'

volumes:
  blaze-data:
  hapi-data:

services:
  blaze:
    image: "samply/blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "https://dev-keycloak.grafm.de/auth/realms/blaze"
      BASE_URL: "http://localhost:9090"
    ports:
      - "9090:8080"
    volumes:
      - "blaze-data:/app/data"

  hapi:
    image: "hapiproject/hapi:latest"
    ports:
      - "8082:8080"
    volumes:
      - hapi-data:/data/hapi
    environment:
      hapi.fhir.default_encoding: json
      hapi.fhir.: json
      hapi.fhir.server_address: "http://localhost:8082/fhir"

